-- create tables: BEGIN
DROP TABLE IF EXISTS parts CASCADE;
CREATE TABLE parts(
    id INT8 generated by default as identity,
    created DATE,
    last_update DATE,
    name VARCHAR(255),
    number VARCHAR(255),
    other_file VARCHAR(255),
    pdf VARCHAR(255),
    status VARCHAR(255),
    type VARCHAR(255),
    PRIMARY KEY (id),
    UNIQUE(number)
);

DROP TABLE IF EXISTS rates CASCADE;
CREATE TABLE rates(
    id INT8 generated by default as identity,
    rate INT8,
    replacement INT8,
    assembly_id INT8,
    part_id INT8,
    PRIMARY KEY (id),
    UNIQUE(assembly_id, part_id)
);
-- create tables: END
---------------------------------------------------------------------------
-- add foreign keys: BEGIN
ALTER TABLE rates
    ADD CONSTRAINT fk_assembly_id
        FOREIGN KEY (assembly_id) REFERENCES parts(id);

ALTER TABLE rates
    ADD CONSTRAINT fk_part_id
        FOREIGN KEY (part_id) REFERENCES parts(id);
-- add foreign keys: END
---------------------------------------------------------------------------
-- add limited constraints: BEGIN

-- add limited constraints: END
---------------------------------------------------------------------------
-- populate TABLE parts: BEGIN
INSERT INTO parts(number, name, type, status, created, last_update)
    VALUES
            ('01.000.000.000 СБ', 'Блок питания', 'ASSEMBLY', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.000.001', 'Золотник', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.000.002', 'Корпус', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.000.003', 'Направляющая', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.000.004', 'Пробка', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.000.005', 'Пружина', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.000.006', 'Винт', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.000.007', 'Направляющая', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.000.008', 'Пружина', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),

            ('01.000.100.000 СБ', 'Клапан обратный', 'ASSEMBLY', 'DESIGN', '2022-11-13', '2022-11-13'),
            ('01.000.100.001', 'Корпус', 'PART', 'DESIGN', '2022-11-13', '2022-11-13'),

            ('B.000.001', 'Шарик', 'STANDARD_PART', 'NONE', '2022-11-13', '2022-11-13'),
            ('B.000.002', 'Шарик', 'STANDARD_PART', 'NONE', '2022-11-13', '2022-11-13'),

            ('N.000.001', 'Гайка', 'STANDARD_PART', 'NONE', '2022-11-13', '2022-11-13'),

            ('RR.000.003', 'Кольцо стопорное', 'STANDARD_PART', 'NONE', '2022-11-13', '2022-11-13'),
            ('RR.001.002', 'Кольцо стопорное', 'STANDARD_PART', 'NONE', '2022-11-13', '2022-11-13'),

            ('OR.000.001', 'Кольцо резиновое', 'STANDARD_PART', 'NONE', '2022-11-13', '2022-11-13'),
            ('OR.000.002', 'Кольцо резиновое', 'STANDARD_PART', 'NONE', '2022-11-13', '2022-11-13'),

            ('GA.000.001', 'Гидроаккумулятор', 'BUY_PART', 'NONE', '2022-11-13', '2022-11-13'),

            ('WRM.000.001', 'Шайба резинометаллическая', 'BUY_PART', 'NONE', '2022-11-13', '2022-11-13');
-- populate TABLE parts: END
---------------------------------------------------------------------------
-- populate TABLE rates: BEGIN
INSERT INTO rates(rate, replacement, assembly_id, part_id)
    VALUES
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.100.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.100.001')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.100.000 СБ'),
                    (SELECT id FROM parts WHERE number='B.000.001')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.100.000 СБ'),
                    (SELECT id FROM parts WHERE number='OR.000.002')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.100.000 СБ'),
                    (SELECT id FROM parts WHERE number='RR.001.002')),


            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.000.001')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.000.002')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.000.003')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.000.004')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.000.005')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.000.006')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.000.007')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.000.008')),
            (2, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='01.000.100.000 СБ')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='B.000.001')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='B.000.002')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='GA.000.001')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='N.000.001')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='RR.000.003')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='WRM.000.001')),
            (1, -1,
                    (SELECT id FROM parts WHERE number='01.000.000.000 СБ'),
                    (SELECT id FROM parts WHERE number='OR.000.001'));
-- populate TABLE rates: END
---------------------------------------------------------------------------