DROP TABLE IF EXISTS parts_changes CASCADE;
CREATE TABLE parts_changes(
    id INT8 generated by default as identity,
    part_id INT8,
    update VARCHAR(255),
    action VARCHAR(255),
    object TEXT,
    PRIMARY KEY (id)
);